name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true  # required for caching
          show-channel-urls: true
          channel-priority: strict
          activate-environment: osmnx-examples
          environment-file: environment-tests.yml

      - name: Test environment
        run: |
          conda list
          conda info --all
          ipython -c "import igraph, osmnx; print('OSMnx version', osmnx.__version__)"

      - name: Lint notebooks
        run: |
          nbqa isort ./notebooks/*.ipynb --line-length 100 --sl --check-only
          nbqa black ./notebooks/*.ipynb --line-length 100 --check --diff
          nbqa flake8 ./notebooks/*.ipynb --max-line-length 100

      - name: Test notebooks
        run: |
          cd ./notebooks
          rm -r -f *.py
          jupyter nbconvert --to python *.ipynb
          for f in *.py; do ipython "$f"; done
          rm -r -f *.py
